name: CI/CD - Azure Web App com ACR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Login no Azure via Service Principal
    - name: Login no Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Login no ACR
    - name: Login no Azure Container Registry
      run: |
        echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_LOGIN_SERVER }} \
          --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    # Build da imagem Docker
    - name: Build da imagem
      run: |
        docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.CONTAINER_IMAGE_NAME }}:latest .

    # Push da imagem para o ACR
    - name: Push da imagem
      run: |
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.CONTAINER_IMAGE_NAME }}:latest

    # Atualiza o Web App para usar a nova imagem
    - name: Deploy para o Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.CONTAINER_IMAGE_NAME }}:latest
